// Generated by https://quicktype.io

export interface User {
  id: number;
  nombre: string;
  apellido: string;
  detail: Detail[];
  saldo: number;
}

export interface Detail {
  ingresos: number;
  egresos: number;
}
